changelog:
  exclude:
    authors:
      - ApodiniBot
  categories:
    - title: Semantic Version Major
      labels:
        - needs version bump
    - title: Semantic Version Minor
      labels:
        - bug
        - enhancement
    - title: Other Changes
      labels:
        - "*"
