version: 0.0
os: linux
files:
  - source: ./deployment/docker-compose-deploy.yml
    destination: /home/ec2-user/webservice/docker-compose.yml
  - source: ./env
    destination: /home/ec2-user/webservice/.env
hooks:
  AfterInstall:
    - location: deployment/setup.sh
      timeout: 1800
      runas: ec2-user
  ApplicationStart:
    - location: deployment/run.sh
      timeout: 1800
      runas: ec2-user
