version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/webservice/
hooks:
  AfterInstall:
    - location: setup.sh
      timeout: 1800
      runas: root
  ApplicationStart:
    - location: run.sh
      timeout: 1800
      runas: root
