{
 "title": "ApodiniObserve example",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(response_time_nanoseconds{quantile=\"0.5\"}[60m])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "rate(request_counter[5m])", "legendFormat": "{{endpoint}}" }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "rate(error_counter[5m])", "legendFormat": "{{endpoint}}" }
   ]
  }
 ]
}