name: Build and Test

on:
  pull_request:
    paths:
      - 'WebService/**'
  workflow_dispatch:

jobs:
  docker-compose-test:
    name: Docker Compose Test
    uses: Apodini/.github/.github/workflows/docker-compose-test.yml@v1
    with:
      testscript: test.sh
  swiftlint:
    name: SwiftLint
    uses: Apodini/.github/.github/workflows/swiftlint.yml@v1
  build_and_test:
    name: Build and Test
    uses: Apodini/.github/.github/workflows/build-and-test.yml@v1
    with:
      path: ./WebService
      packagename: ScienceLabWebservice
      testdocc: false
      supportsmacos11: false
      aptgetdependencies: libsqlite3-dev
      yumdependencies: sqlite-devel
